name: Build VM contain docker image

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./docker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t vm-image -f vm-container.dockerfile .

      - name: Push Docker image
        run: |
          docker tag my-vm-image -image:latest
          docker push webvm/my-vm-image:latest
