name: Build VM contain docker image

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./docker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push Docker image to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./vm-container.dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/webvm:latest