name: Build VM contain docker image

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./docker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t vm --file vm-container.dockerfile .

      - name: Push Docker image
        run: |
          docker tag vm moonpatel/webvm:latest
          docker push moonpatel/webvm:latest
